### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by Mutai-Gilbert** [Mutai-Gilbert/TVamaze-API-based-webapp#62]
In this pull request we were able to:
- Use Kanban board with filled-in tasks that have categories and time estimations to assign work in group.

The link to our project is attached below. We are two in our group  @Mutai-Gilbert  and @Roland-Ntwali 
https://github.com/Mutai-Gilbert/TVamaze-API-based-webapp/projects/1

**Comment by Abenezer-Tilahun** [comment]
Hi @Mutai-Gilbert   @Roland-Ntwali 
 
Great job for implemented  the Project requirement  , but there are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻

✔️ Good Job for mention how many people are in your Group
✔️ Good job for set up a kanban board for the JavaScript group capstone.

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️

- [x] As stated in the project requirement Kindly make sure that you provide the link to setup Kanban board for the project , but in the case of yours you submitted the link to the GitHub project please fix it. It should be this [link] (https://github.com/Mutai-Gilbert/TVamaze-API-based-webapp/projects/1)
- [x] Kindly I recommend you to make sure that all cards are assigned to team members. there should be a circle with the user's avatar on each card. See the example below:
![image](https://user-images.githubusercontent.com/93598189/224801357-4bce6a4e-83a2-425b-b459-b67ee36722b0.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jasonfelice** [comment]
Hi @Mutai-Gilbert & @Roland-Ntwali, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<p align="center"><img  src="https://media2.giphy.com/media/Zcm5DaspYzhTxstkF4/giphy.gif?cid=ecf05e472vkr75z01b5qlseyap0ylpyn6krdcf0fokyey0cx&rid=giphy.gif&ct=g"/></p>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
